#include<iostream>
using namespace std;
// THIS IS CALLED CALL BY VALUE.
void increment(int a)  // HERE a IS THE FORMAL PARAMETER. FORMAL PARAMETER IS THE VALUE RECIEVED BY THE FUNCTION. 
{
    a++;
}

int main()
{
   int a = 10;
   increment(a);  
   
   /* HERE a IS THE ACTUAL PARAMETER. ACTUAL PARAMETER IS THE VALUE PASSED TO THE FUNCTION WHILE CALLING THE FUNCTION.
    HERE a IS THE LOCAL VARIABLE OF THE FUNCTION. THIS a IS NOT THE SAME AS THE VARIABLE a DECLARED EARLIER.
    ALSO NOTE THAT IN CALL BY VALUE, ONLY THE VALUE OF THE VARIABLE AND NOT THE VARIABLE IS PASSED TO THE FUNCTION. */
    
   cout<<a<<endl;
   return 0;
}